# Generated by Django 3.2.12 on 2024-10-10 08:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBaseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BachatGatRegistration',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BachatGat.mybasemodel')),
                ('bachatgat_name', models.CharField(max_length=255)),
                ('start_month', models.CharField(max_length=50)),
                ('start_year', models.CharField(max_length=4)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('member_count', models.IntegerField()),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('register_by', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            bases=('BachatGat.mybasemodel',),
        ),
        migrations.CreateModel(
            name='MemberRegistration',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BachatGat.mybasemodel')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('entry_month', models.CharField(max_length=20)),
                ('entry_year', models.IntegerField()),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('bachatgat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BachatGat.bachatgatregistration')),
            ],
            bases=('BachatGat.mybasemodel',),
        ),
    ]
